networks:
  echo-server:
    name: "echo-server"

services:
  echo-server:
    build:
      context: .
    container_name: echo-server
    network_mode: host
    #      - host
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    network_mode: host
    #      - host
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:latest  # must be >=1.35 for OTLP support
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    network_mode: host
    #      - host
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686