---
extensions:
  basicauth/otlp:
    client_auth:
      username: 664205
      password: ${GRAFANA_CLOUD_API_KEY}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: debug
  otlphttp/grafana-cloud:
    endpoint: https://otlp-gateway-prod-us-central-0.grafana.net/otlp
    auth:
      authenticator: basicauth/otlp
  otlphttp/mimir-local:
    endpoint: http://127.0.0.1:8000/otlp
    # use for multi-tenant Mimir
    # headers:
    #  "X-Scope-OrgId": "1"
  prometheusremotewrite/grafana-cloud:
    # not in use, now that pushing to Grafana OTEL endpoint is working
    endpoint: https://prometheus-us-central1.grafana.net/api/prom/push
    auth:
      authenticator: basicauth/otlp
    resource_to_telemetry_conversion:
      enabled: true  # Convert resource attributes to metric labels

service:
  extensions: [ basicauth/otlp ]
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ logging, otlphttp/mimir-local ]
    traces:
      receivers: [ otlp ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      exporters: [ logging ]
